title: Yelling at Clouds

email: anthony.tarola@gmail.com
twitter_username: atarola
github_username: atarola

markdown: kramdown
highlighter: pygments
plugins:
  - jekyll-feed
  - jekyll-paginate

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://atarola.dev" # the base hostname & protocol for your site, e.g. http://example.com

paginate: 5
